### ISSUE TITLE
License to use the footprints

### ISSUE THREAD

**Issue by Gondolindrim** [skullydazed/clueboard_eagle#3]
Hey Skully,

I was wondering if I could use the footprints to develop some boards. My plans are to develop those boards to the brazilian market, and international after I built some marketbase here. I intend to use them commercially (sell the boards to the community).

Thanks!

**Comment by skullydazed** [comment]
Thanks for getting in touch, this is perfectly fine! From my understanding Brazil needs more local manufacturers to help with this hobby. You have my explicit permission to use these for commercial purposes.

Keep us updated with your progress in discord. :)
